### ISSUE TITLE
Lattest TBRPG Error

### ISSUE THREAD

**Issue by FleksisLV** [insthync/unity-tbrpg-pun-arena#1]
Hello, I tried to install the arena plugin today and I'm getting an error.

Assets\ArenaRealtimeBattle\Scripts\UI\UIPunRoomPassword.cs(1,7): error CS0246: The type or namespace name 'RealtimeArena' could not be found (are you missing a using directive or an assembly reference?)

I installed installed the plugin, and PUN2 I am getting the error given above. 

Any idea why i get this error  ?

Thanks 👍

**Comment by insthync** [comment]
Maybe because while I working it has  in my project it has https://github.com/insthync/unity-tbrpg-realtime-arena in my project, and I just uses codes from there, I will fix it.

**Comment by insthync** [comment]
Fixed
